### ISSUE TITLE
Error when submit code

### ISSUE THREAD

**Issue by itzdenki** [HimitZH/HOJ#64]
When I submitted Java, C#, JavaScript Node, JavaScript V8, Ruby, Rust, Python2 (PyPy2), Python3 (PyPy3) getting error but all of C, C++, Golang, PHP is ok
I'm using standAlone version and just run the command in the docs
![image](https://github.com/user-attachments/assets/1781245d-9c95-437f-87c3-afacc221d11a)

**Comment by HimitZH** [comment]
Please confirm if your hoj is the latest version and if the deployed Linux system version is as shown in the documentation. I suggest using Ubuntu 18.04 and above with AMD 64 system architecture.

**Comment by itzdenki** [comment]
I am using the latest version of hoj but I am using Ubuntu 22.04 and ARM

**Comment by HimitZH** [comment]
What version of docker image is used for the `hoj-judgeserver` inside `docker-compose.yml` file,

**Comment by HimitZH** [comment]
You may need to switch the image as follows
`  hoj-judgeserver:
    #just support amd64
    # image: registry.cn-shenzhen.aliyuncs.com/hcode/hoj_judgeserver
    #support amd64、arm64 
    image: himitzh/hoj_judgeserver  
    container_name: hoj-judgeserver`

**Comment by HimitZH** [comment]
You may need to switch the image as follows：
```yaml
  hoj-judgeserver:
    #just support amd64
    # image: registry.cn-shenzhen.aliyuncs.com/hcode/hoj_judgeserver
    #support amd64 or arm64，use this
    image: himitzh/hoj_judgeserver
    container_name: hoj-judgeserver
    restart: always
```
